SelfIntroMVC4/ViewModels/AboutMeModel.cs
using SelfIntroMVC4.Types;
using System;
using System.ComponentModel.DataAnnotations;

namespace SelfIntroMVC4.ViewModels
{
    public class AboutMeModel
    {
        [Display(Name="姓名")]
        public string Name { get; set; }
        [Display(Name="綽號")]
        public string NickName { get; set; }
        [Display(Name="英文名字")]
        public string EnglishName { get; set; }
        [Display(Name="性別")]
        public SexType Sex { get; set; }
        [Display(Name="生日")]
        public DateTime BirthDay { get; set; }
    }
}

SelfIntroMVC4/ViewModels/HomeModel.cs
using System.ComponentModel.DataAnnotations;

namespace SelfIntroMVC4.ViewModels
{
    public class HomeModel
    {
        [Display(Name="關於我")]
        public string ShortAboutMe { get; set; }
        [Display(Name = "自傳")]
        public string ShortAutobiography { get; set; }
        [Display(Name = "聯絡我")]
        public string Contact { get; set; }
    }
}

SelfIntroMVC4/ViewModels/SkillModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SelfIntroMVC4.ViewModels
{
    public class SkillModel
    {
    }
}

SelfIntroMVC4/Controllers/AboutMeController.cs
using SelfIntroMVC4.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SelfIntroMVC4.Controllers
{
    public class AboutMeController : Controller
    {
        // GET: AboutMe
        public ActionResult Index()
        {
            var model = new AboutMeModel();
            model.Name = "蕭瑋彥";
            model.NickName = "小白";
            model.EnglishName = "Willian";
            model.BirthDay = DateTime.Parse("1986/12/01");
            return View(model);
        }
    }
}

SelfIntroMVC4/Controllers/AutobiographyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SelfIntroMVC4.Controllers
{
    public class AutobiographyController : Controller
    {
        // GET: Autobiography
        public ActionResult Index()
        {
            return View();
        }
    }
}

SelfIntroMVC4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SelfIntroMVC4.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

SelfIntroMVC4/Controllers/SkillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SelfIntroMVC4.Controllers
{
    public class SkillController : Controller
    {
        // GET: Skill
        public ActionResult Index()
        {
            return View();
        }
    }
}

SelfIntroMVC4/Controllers/ToolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SelfIntroMVC4.Controllers
{
    public class ToolsController : Controller
    {
        // GET: Tools
        public ActionResult Index()
        {
            return View();
        }
    }
}

SelfIntroMVC4/Views/AboutMe/Index.cshtml
@model SelfIntroMVC4.ViewModels.AboutMeModel

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>關於我</title>
</head>
<body>
    <div class="table-responsive">
        <table class="table table-bordered">
            <tr>
                <th>@Html.LabelFor(m=>m.Name)</th>
                <td>@Html.DisplayFor(m=>m.Name)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(m=>m.NickName)</th>
                <td>@Html.DisplayFor(m=>m.NickName)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(m=>m.EnglishName)</th>
                <td>@Html.DisplayFor(m=>m.EnglishName)</td>
            </tr>
            <tr>
                <th>@Html.LabelFor(m=>m.BirthDay)</th>
                <td>@Model.BirthDay.ToString("yyyy/MM/dd")</td>
            </tr>
        </table>
    </div>
</body>
</html>

SelfIntroMVC4/Views/Autobiography/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

SelfIntroMVC4/Views/Home/Index.cshtml
@model SelfIntroMVC4.ViewModels.HomeModel
<html lang="en">
<head>
</head>
<body>

    <!-- Heading Row -->
    <div class="row">
        <div class="col-md-8">
            <img class="img-responsive img-rounded" src="~/Content/image/FrontBg.jpg" alt="">
        </div>
        <!-- /.col-md-8 -->
        <div class="col-md-4">
            <h1>Business Name or Tagline</h1>
            <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
            <a class="btn btn-primary btn-lg" href="#">Call to Action!</a>
        </div>
        <!-- /.col-md-4 -->
    </div>
    <!-- /.row -->
    <hr>
    <!-- Call to Action Well -->
    @*<div class="row">
        <div class="col-lg-12">
            <div class="well text-center">
                This is a well that is a great spot for a business tagline or phone number for easy access!
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>*@
    <!-- /.row -->
    <!-- Content Row -->
    <div class="row">
        <div class="col-md-4">
            <h2>關於我</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe rem nisi accusamus error velit animi non ipsa placeat. Recusandae, suscipit, soluta quibusdam accusamus a veniam quaerat eveniet eligendi dolor consectetur.</p>
            <a class="btn btn-default" href="@Url.Action("Index", "AboutMe")">更多...</a>
        </div>
        <!-- /.col-md-4 -->
        <div class="col-md-4">
            <h2>自傳</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe rem nisi accusamus error velit animi non ipsa placeat. Recusandae, suscipit, soluta quibusdam accusamus a veniam quaerat eveniet eligendi dolor consectetur.</p>
            <a class="btn btn-default" href="@Url.Action("Index", "Autobiography")">更多...</a>
        </div>
        <!-- /.col-md-4 -->
        <div class="col-md-4">
            <h2>聯絡方式</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe rem nisi accusamus error velit animi non ipsa placeat. Recusandae, suscipit, soluta quibusdam accusamus a veniam quaerat eveniet eligendi dolor consectetur.</p>
            <a class="btn btn-default" href="@Url.Action("Index", "Contact")">更多...</a>
        </div>
        <!-- /.col-md-4 -->
    </div>
</body>
</html>

SelfIntroMVC4/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Small Business - Start Bootstrap Template</title>
    <!-- jQuery -->
    <script src="~/Content/js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/css/small-business.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <img src="~/Content/image/logo76183173.png" alt="">
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "Home")">首頁</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "AboutMe")">關於我</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Autobiography")">自傳</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Skill")">專長</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Contact")">聯絡方式</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    <div class="container">
        @RenderBody()
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->
</body>
</html>